const key = 'at-the-table-v1';
const sampleMeals = [
  {id:1,name:'Overnight oats',slot:'Breakfast',ingredients:['oats','milk','berries'],notes:'Make the night before'},
  {id:2,name:'Eggs on toast',slot:'Breakfast',ingredients:['eggs','bread','butter'],notes:'10 minutes'},
  {id:3,name:'Yogurt & fruit',slot:'Snack',ingredients:['yogurt','berries','banana'],notes:'Easy default'},
  {id:4,name:'Turkey sandwich',slot:'Lunch',ingredients:['turkey','bread','lettuce','cheese'],notes:''},
  {id:5,name:'Chicken tacos',slot:'Dinner',ingredients:['chicken','tortillas','avocado','salsa'],notes:'15 minutes'},
  {id:6,name:'Salmon rice bowls',slot:'Dinner',ingredients:['salmon','rice','cucumber','avocado'],notes:'Weeknight favorite'},
  {id:7,name:'Pasta with meat sauce',slot:'Dinner',ingredients:['pasta','ground beef','tomato sauce','parmesan'],notes:'Good for leftovers'},
];
let state = JSON.parse(localStorage.getItem(key)) || {meals:sampleMeals, pantry:['chicken','tortillas','avocado','salsa','eggs','bread','oats','milk','berries','rice'], avoid:['dates','papaya','flax'], plan:{}};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const save=()=>localStorage.setItem(key,JSON.stringify(state));
const clean=s=>s.trim().toLowerCase();
const escape=s=>String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function safe(meal){return !meal.ingredients.some(i=>state.avoid.includes(clean(i)))}
function options(slot,except){return state.meals.filter(m=>m.slot===slot&&m.id!==except&&safe(m))}
function choose(slot,except){let a=options(slot,except);return a.length?a[Math.floor(Math.random()*a.length)]:null}
function renderPlan(){let slots=['Breakfast','Snack','Lunch','Dinner']; $('#today-grid').innerHTML=slots.map(slot=>{let m=state.plan[slot]; return `<article class="meal-card"><span class="slot">${slot}</span>${m?`<h3>${escape(m.name)}</h3><p>${escape(m.notes||m.ingredients.slice(0,3).join(' · '))}</p><div class="card-actions"><button data-reroll="${slot}">Reroll</button><button data-clear="${slot}">Clear</button></div>`:`<h3>Open</h3><p>Pick a meal when you’re ready.</p><div class="card-actions"><button data-reroll="${slot}">Choose one</button></div>`}</article>`}).join('');}
function planDay(){['Breakfast','Snack','Lunch','Dinner'].forEach(s=>state.plan[s]=choose(s,state.plan[s]?.id));save();renderPlan()}
function renderLibrary(){ $('#meal-count').textContent=`${state.meals.length} meals`; $('#meal-list').innerHTML=state.meals.map(m=>`<div class="meal-row"><span class="meal-icon">${m.slot==='Dinner'?'◐':'◌'}</span><div><strong>${escape(m.name)}</strong><small>${escape(m.slot)} · ${escape(m.ingredients.join(', '))}</small></div><button class="text-button" data-edit="${m.id}">Edit</button></div>`).join('');}
function chipHtml(items,type){return items.map(x=>`<span class="chip">${escape(x)} <button data-remove="${escape(x)}" data-type="${type}" aria-label="remove ${escape(x)}">×</button></span>`).join('')}
function renderIngredients(){ $('#pantry-manage').innerHTML=chipHtml(state.pantry,'pantry'); $('#pantry-chips').innerHTML=state.pantry.map(x=>`<button class="chip pantry-choice" data-choice="${escape(x)}">${escape(x)}</button>`).join(''); $('#avoid-list').innerHTML=chipHtml(state.avoid,'avoid');}
function suggestions(){let picked=$$('.pantry-choice.selected').map(b=>clean(b.dataset.choice)); let meals=state.meals.filter(safe).map(m=>({...m,missing:m.ingredients.filter(i=>!picked.includes(clean(i)))})).sort((a,b)=>a.missing.length-b.missing.length); $('#suggestions').innerHTML=meals.length?meals.map(m=>`<article class="suggestion"><span class="slot">${m.slot}</span><h3>${escape(m.name)}</h3><p class="${m.missing.length?'':'good'}">${m.missing.length?`Needs: ${escape(m.missing.join(', '))}`:'You have everything'}</p></article>`).join(''):'<p class="empty">Add a meal to see suggestions.</p>'}
function openMeal(id){let m=state.meals.find(m=>m.id===id)||{}; $('#meal-form-title').textContent=id?'Edit meal':'Add a meal'; $('#meal-id').value=m.id||''; $('#meal-name').value=m.name||''; $('#meal-slot').value=m.slot||'Dinner'; $('#meal-ingredients').value=(m.ingredients||[]).join(', '); $('#meal-link').value=m.link||''; $('#meal-notes').value=m.notes||''; $('#meal-dialog').showModal()}
function parseImport(text){let added=0;text.split('\n').map(x=>x.trim()).filter(Boolean).forEach(line=>{let p=line.split('|').map(x=>x.trim());let name='',slot='Dinner',ingredients=[];if(p.length>=2){[name,slot,...ingredients]=p;ingredients=ingredients.join('|').split(',').map(clean).filter(Boolean)}else{let match=line.match(/^(Breakfast|Snack|Lunch|Dinner):\s*(.+)$/i);if(match){slot=match[1][0].toUpperCase()+match[1].slice(1).toLowerCase();match[2].split(',').forEach(n=>state.meals.push({id:Date.now()+added++,name:n.trim(),slot,ingredients:[],notes:''}));return}else name=line}if(name)state.meals.push({id:Date.now()+added++,name,slot:slot[0].toUpperCase()+slot.slice(1).toLowerCase(),ingredients,notes:''})});save();renderLibrary();}
$('#date-label').textContent=new Intl.DateTimeFormat('en-US',{weekday:'long',month:'long',day:'numeric'}).format(new Date()).toUpperCase();
$('#plan-day').onclick=planDay; $('#find-meals').onclick=suggestions; $('#open-add').onclick=()=>openMeal(); $('#open-import').onclick=()=>$('#import-dialog').showModal(); $('#share-button').onclick=()=>$('#share-dialog').showModal();
$$('.mode').forEach(b=>b.onclick=()=>{$$('.mode').forEach(x=>x.classList.toggle('active',x===b));$('#quick-panel').classList.toggle('hidden',b.dataset.mode!=='quick');$('#pantry-panel').classList.toggle('hidden',b.dataset.mode!=='pantry')});
document.addEventListener('click',e=>{let b=e.target.closest('[data-reroll],[data-clear],[data-edit],[data-remove],[data-choice]');if(!b)return;if(b.dataset.reroll){let s=b.dataset.reroll;state.plan[s]=choose(s,state.plan[s]?.id);save();renderPlan()}if(b.dataset.clear){delete state.plan[b.dataset.clear];save();renderPlan()}if(b.dataset.edit)openMeal(+b.dataset.edit);if(b.dataset.choice){b.classList.toggle('selected');suggestions()}if(b.dataset.remove){let f=b.dataset.type==='pantry'?'pantry':'avoid';state[f]=state[f].filter(x=>x!==b.dataset.remove);save();renderIngredients();suggestions()}});
$('#add-pantry').onclick=()=>{let v=clean($('#pantry-input').value);if(v&&!state.pantry.includes(v)){state.pantry.push(v);save();renderIngredients()}$('#pantry-input').value=''};$('#add-avoid').onclick=()=>{let v=clean($('#avoid-input').value);if(v&&!state.avoid.includes(v)){state.avoid.push(v);save();renderIngredients();renderPlan()}$('#avoid-input').value=''};
$('#meal-form').addEventListener('submit',e=>{e.preventDefault();let id=+$('#meal-id').value||Date.now(),m={id,name:$('#meal-name').value.trim(),slot:$('#meal-slot').value,ingredients:$('#meal-ingredients').value.split(',').map(clean).filter(Boolean),link:$('#meal-link').value.trim(),notes:$('#meal-notes').value.trim()};let old=state.meals.findIndex(x=>x.id===id);old>=0?state.meals[old]=m:state.meals.push(m);save();renderLibrary();renderPlan();$('#meal-dialog').close()});
$('#do-import').onclick=e=>{e.preventDefault();parseImport($('#import-text').value);$('#import-text').value='';$('#import-dialog').close()};
renderPlan();renderLibrary();renderIngredients();
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
